Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -11,7 +11,14 @@ jobs:
       - uses: actions/checkout@v4
       - id: set-matrix
         run: |
-          matrix=$(yq -oj -I0 '.' config/build.yaml)
+          # Verifica dove si trova build.yaml e genera il JSON
+          if [ -f "config/build.yaml" ]; then
+            matrix=$(yq -oj -I0 '.' config/build.yaml)
+          elif [ -f "build.yaml" ]; then
+            matrix=$(yq -oj -I0 '.' build.yaml)
+          else
+            echo "Errore: file build.yaml non trovato!" && exit 1
+          fi
           echo "matrix=$matrix" >> $GITHUB_OUTPUT
 
   build:
